'From Cuis 5.0 of 7 November 2016 [latest update: #3485] on 25 November 2018 at 5:49:30 pm'!
'Description Please enter a description for this package'!
!provides: 'IA-EN-Dictionary' 1 0!
SystemOrganization addCategory: #'IA-EN-Dictionary'!


!classDefinition: #IEDict category: #'IA-EN-Dictionary'!
Object subclass: #IEDict
	instanceVariableNames: ''
	classVariableNames: 'DictData'
	poolDictionaries: ''
	category: 'IA-EN-Dictionary'!
!classDefinition: 'IEDict class' category: #'IA-EN-Dictionary'!
IEDict class
	instanceVariableNames: ''!


!IEDict commentStamp: '<historical>' prior: 0!
I'm learning Cuis-Smalltalk.!
